---
title: "US Top 10 Universities 2018"
author: "thenuv"
date: "6 August 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Reported on : `r format(Sys.Date(), "%B %d %Y")`

```{r echo=FALSE, message=FALSE, warning=FALSE}

library(leaflet )
df_unv <- read.csv("TopUniversityLocations.csv")
df_unv %>% 
	leaflet(width = "100%") %>%
	addTiles() %>%
	addMarkers(popup=paste(df_unv$UniversityName, ":",  "Rank", df_unv$Rank),
	           label = paste(df_unv$UniversityName, ":",  "Rank", df_unv$Rank))


```

*Hover/Click the location in the map to know the University name and its Rank*
 
 

```{r, echo=FALSE, comment=''}
print(df_unv[order(df_unv$Rank),c(4,3)], row.names = FALSE)

```

### Reference
*This data was refered from QS Top Universities Ranking.*
https://www.topuniversities.com/university-rankings-articles/world-university-rankings/top-universities-us-2018

*This is prepared for personal assignment for a course on Data Science*

